### ISSUE TITLE
新安装时出现下面的错误

### ISSUE THREAD

**Issue by koiding** [luisedware/CowCat#6]
Cannot use App\Facades\MenuRepository as MenuRepository because the name is already in use

**Comment by korn519** [comment]
命名空间问题，注释掉就好了

**Comment by luisedware** [comment]
我把命名空间的问题修好了，因为自身没有这个问题，很难重现，所以修复的时间比较长，不好意思。有时间的话，麻烦从 github pull 下来吧。
